/*
 * ToDoList Restful API
 *
 * OpenAPI for ToDoList Restful API
 *
 * API version: 1
 * Contact: mhdianrush@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001 struct {
	Success bool `json:"success,omitempty"`
}
